.gitignore, examples/live-updates.js, lib/Pipedrive.js, lib/channel.js, lib/listener.js, package.json
* Client now exposes .on() method which can be used to set up event listeners for actions taken on the account that the authenticated user can access as they happen in near-real-time. This is highly experimental at this stage, and thus not publicly documented in readme.
* Client init takes second argument as object of options now.
=> Add alpha version of channel support for live listeners

lib/channel.js, package.json
Swapping to sockjs-client allows package to work with recent versions of Node (4.x), though I'm unsure if it has any impact on older versions (untested). Anyway, sockjs-client-node is deprecated.
=> Swap sockjs-client-node with sockjs-client

lib/Pipedrive.js
Allow user to pass params to getAll
- Useful for requests that takes optional params (Activities, Deals)
=> Add params option to getAll

lib/Pipedrive.js
Return when calling the callback when an error occurs.  Prevent
retrieving of next page (which will fail again).
A simple scenario would be an Invalid API token.
=> Prevent getAll looping indefinitely when error occurs

lib/CollectionItem.js
Client calls like https://github.com/pipedrive/client-nodejs#objectmergewithid-fn-callback
should return the full object with all it's methods present (like duplicate, merge)
right now they only return an object with the raw attributes
p.s. added save() to return object with methods too
=> Ind-13 - deal.merge & duplicate does not return full deal object

examples/live-updates.js, lib/channel.js
* Since mid last year, websocket event handlers functionality was not functioning properly due to underlying changes in the channel domain structure.
* This pull request fixes how the websocket domain name is acquired and how the connection is established.
=> Re-implement websocket event handlers functionality

README.md, examples/list-deals.js, lib/Collection.js, lib/restHandlers.js, package.json, test/integration/client.js, test/unit/client.js, test/unit/index.js, test/unit/restHandlers.js
* **Adds support for related objects fetching.** In related objects (passed down as the sixth argument when fetching objects, or lists of objects) , Pipedrive API passes down things like pictures of persons, relevant user profile data etc that would be needed to properly render the underlying objects to a human being.
* Since related objects do not represent complete objects, they are not wrapped as collectionItems and thus have to be used as data stubs only. This is intentional by design.
=> Add support for related objects fetching

.travis.yml, Jenkinsfile, package-lock.json, package.json
* Only node versions 6, 8 and 10 are now supported
* Updated mocha library dependency to 5.2.0 to remove vulnerability issues
=> v6.0.0 Dropped support for old node versions

package-lock.json, package.json
There was a vulnerability with url-parse, which is used by sockjs-client.
Vulnerability is fixed, tests are passing.
=> url-parse vulnerability fixed

lib/CollectionItem.js, test/unit/CollectionItem.js
_I didn't see any contributor guidelines, but trying this anyway because the issue is a showstopper for us (since the uncaught error crashes Node)._
Fixes #74.
When item.save(callbackFn) is called with invalid input, the server rejects the request with a 400 response, as expected. The client, however, does not call the given callbackFn to provide the error to the caller. Instead, an uncaught error is thrown trying to wrap the `null` data into a collection.
Not only does this behavior violate the specified contract by not calling the callback function, but the uncaught error can crash Node completely, with no way for an outsider to `try`/`catch` the save() call itself, since the error happens in its own callback.
This fix adds unit tests demonstrating the problem, and fixes the problem by …
=> Fix for item.save() never calling its callback function

package-lock.json, package.json
Current lodash version contains a high severity vulnerability.
This PR fixes it.
=> Lodash Vulnerability Fixed

lib/Controllers/DealsController.js
Removed parsing of getDetailsOfADealAction to make it possible to see dynamic fields.
Added dynamic field update support using spread operators in updateADealAction method.
This PR should fix issue #114
=> Dynamic deal fields support

lib/Controllers/PersonsController.js
This PR deletes docs about an attribute that breaks addAPerson method. Did not fix in code right now to reduce merge errors.
This was created in response to issue #129
=> Deleted misleading docs

lib/Controllers/FilesController.js, lib/Http/Client/RequestClient.js
Issue: https://github.com/pipedrive/client-nodejs/issues/138
Details:
`/files/{id}/download` used to invoke `JSON.parse` for response body. In case if a respone is some binary (file) JSON.parse  will fail.
Test fix:
```javascript
const Pipedrive = require('../client-nodejs');  // fix-files branch
const API_TOKEN = 'token'; // replace to yours
const FILE_ID = 'file id you want to download'; // replace to yours
const fs = require('fs')
const path = require('path')
Pipedrive.Configuration.apiToken = API_TOKEN;
function getFile(fileId) {
return new Promise((resolve, reject) => {
Pipedrive.FilesController.getDownloadOneFile(fileId, (err, res) => {
if (err) {
reject(err)
} else {
resolve(res);
}
})
});
}
async function test() {
try {
const response = await getFile(FILE_ID);
fs.writeFileSync( …
```
=> Issue - 138, remove JSON.parse for file's response

README.md
The initialization of the `input` type shown in the examples is misleading. It creates an array type, and then it fills the attributes as if it were a dictionary. The program still runs, but the type is not adequate.
=> change array for object type in example snippets

README.md
https://pipedrive.atlassian.net/secure/RapidBoard.jspa?rapidView=344&projectKey=GRAL&modal=detail&selectedIssue=GRAL-1930
The initialization of the `input` type shown in the examples is misleading. It creates an array type, and then it fills the attributes as if it were a dictionary. The program still runs, but the type is not adequate.
=> GRAL-1930: change array for object type in example snippets

test/functional/access-token.test.js, test/functional/authorisation.test.js, test/functional/automatic-token-refresh.test.js
In scope of this PR existing functional tests are fixed
- tests now expect the new error structure
- Client id and secret are not passed in URL for /oauth/token, so now mockserver requests are correctly matched
- Check correct Authorization header
=> GRAL-2141 fix functional tests

package.json
In the scope of this PR `test` script is added in order to support flawless npm package publish flow. As there aren't any unit tests for now, the script just runs echo command similar to here: https://github.com/pipedrive/client-nodejs/blob/master/package.json#L27
=> GRAL-2142 add test script

test/functional/environment.js
If functional tests fail, the jest process status code is not passed to the output of `npm run test:functional` which means that there isn't a good way to identify if tests passed or not.  This change will make sure that correct exit code is passed.
=> GRAL-2484 pass jest status code to process.exit

test/functional/access-token.test.js, test/functional/authorisation.test.js, test/functional/automatic-token-refresh.test.js, test/functional/environment.js, test/functional/utils.js
Functional tests currently use src files to run tests on. During automation we want to test generated SDKs which is in dist folder. This change looks for AUTOMATION env variable and uses dist folder instead as testable files.
=> GRAL-2482 use dist folder for automation functional tests

package-lock.json, package.json
Add the "changelog-updater" package and the "version" script to trigger it.
- Run `npm version major/minor/patch`
- The package.json should get updated according to the argument
- The changes from [Unreleased] should get moved to a new paragraph according to the new package version.
=> Automatically update changelog when publishing new SDK version

CHANGELOG.md, package-lock.json, package.json
- Moving the babel runtime dependency back to dependencies as 
- Added the missing paragraph header to 18.0.0 changelog message
=> Move babel runtime back to deps

CHANGELOG.md, package-lock.json, package.json
- Bumps [json5](https://github.com/json5/json5) from 2.2.1 to 2.2.3. https://github.com/pipedrive/client-nodejs/pull/413
- Updates qs from 6.9.3 to 6.11.0 https://github.com/pipedrive/client-nodejs/pull/400
Updates formidable from 2.0.1 to 2.1.1
- Bumps [decode-uri-component](https://github.com/SamVerschueren/decode-uri-component) from 0.2.0 to 0.2.2. https://github.com/pipedrive/client-nodejs/pull/399
- Updates minimatch from 3.0.4 to 3.1.2 https://github.com/pipedrive/client-nodejs/pull/397
Updates mocha from 8.4.0 to 10.1.0
=> Dependencies bump up

.github/workflows/on-commit.yml, package-lock.json, package.json, test/runtime.js
- Adds a GitHub action that attempts to initialise API client with just production dependencies
- GitHub action should fail if there is runtime error during initialisation
**Testing**
To recreate the issue we've had in past
1. GitHub action failure if babel/runtime package is missing
https://github.com/pipedrive/client-nodejs/actions/runs/3957373657
2. GitHub action succeeds if babel/runtime package exists
https://github.com/pipedrive/client-nodejs/actions/runs/3957393740/jobs/6777711406
=> GRAL-3388 add github action to test api client initialisation

.github/workflows/on-pd-bot-pr-opened.yml
- Adds new GitHub Workflow that on version label added automatically approves and publishes the PR
- This only happens for PRs opened by pipedrive-bot
=> GRAL-3484 new workflow to automatically release pipedrive-bot PRs

CHANGELOG.md, README.md
There is a mistake in a variable name in the README complete code example reported in the issue https://github.com/pipedrive/client-nodejs/issues/479. Fixed that.
Also fixed paragraphs in the changelog.
=> GRAL-3802 fix example in the README

README.md
- updated the default provided example to re-create the apiClient on each request to comply with the warning
```
Warning
The pipedrive.ApiClient.instance has been deprecated.
Please, initialise a new pipedrive.ApiClient() instance separately for each request instead.
```
=> GRAL-4688 update readme sdk example

.github/pull_request_template.md
Add pr template
https://pipedrive.atlassian.net/browse/GRAL-5188
=> GRAL-5188: add pr template

CHANGELOG.md, README.md, package-lock.json, package.json
Tackling those two issues:
https://github.com/pipedrive/client-nodejs/issues/615
https://github.com/pipedrive/client-nodejs/issues/620
* Bump `axios` to latest version `1.9.0`
* Add an example to the README about how to fetch one deal details
=> GRAL-5119 Bump axios, update README
