pipedrive/client-nodejs

lib/Pipedrive.js, package.json
Create a local page `param` that is extended from the passed in
`param`.
=> Fix getAll params

lib/channel.js
Earlier in summer, we introduced multi-channel websockets on the server side. However, the client was left not updated. I added the support for multi-channel similarly to that in the webapp.
=> Implement multi-channel connectivity

lib/Pipedrive.js, test/unit/client.js
* Re-implement minor test improvements to pipedrive.getAll() functionality from #41
=> Implement test improvements from #41

examples/product-variations.js, lib/blueprint.js
- Adds product variations to list of supported sub-objects to be able to update product variation for issue https://github.com/pipedrive/client-nodejs/issues/20
see examples, which update variation of first product:
=> Product variation support

package-lock.json, package.json
Vulnerabilities fixed, tests passed.
=> Vulnerabilities Fix

lib/rest.js, package-lock.json, package.json
Fixes https://github.com/pipedrive/client-nodejs/issues/50
Using `form-data` library to correctly submit multipart content, including binary files. Thanks for @scottsbaldwin for raising the issue and working out the solution.
=> GRAL-826 Use form-data library for multipart content

README.md, package-lock.json, package.json, test/integration/client.js, test/unit/CollectionItem.js
- Updated the minimum engine
- Removed unused dependencies
- Tweaked and documented the running of existing integration tests
=> GRAL-793 tweaks

lib/Controllers/PersonsController.js
Hi, we need to send custom updated fields, and in this moment, Pipedrive SDK does not allow, please accept this PR ASAP. Thank you so much.
=> Add support for custom fields updating person

lib/Controllers/DealsController.js
=> Swapped rest parameters to fix attribute overriding by undefined

README.md, lib/Controllers/FilesController.js
This was created in response to #132 and #135 
Decided to accept either camelCased or snake_cased parameters
=> GRAL-1107 Fix FilesController.addFile method snake_case

lib/Controllers/PersonsController.js
This PR was created in response to issue #128.
This is non permanent fix to the SDK to get the required flow functionality. 
Once the /flow endpoint schemas are defined, this fix should no longer be required.
=> Added allChanges parameter to PersonsController.listUpdatesAboutAPerson

README.md, lib/APIHelper.js, package-lock.json, package.json
The autogenerated documentation and dates helper were misleading/incorrect.
This PR:
* fixes the examples of YYYY-MM-DD date inputs in README
* fixes `stringifyDateTime` function to accept string input and convert to `moment` object if needed
Fixes https://github.com/pipedrive/client-nodejs/issues/133
=> GRAL-1109: YYYY-MM-DD date inputs fix

package.json, test/functional/environment.js
- Changed hardcoded port number to a random port when starting functional tests 
Task : https://pipedrive.atlassian.net/browse/GRAL-2557
=> GRAL-2557 added random port for functional tests

package.json
- added get-port to package.json
=> GRAL-2557 added get-port to package.json

.gitignore, package.json, test/functional/access-token.test.js, test/functional/authorisation.test.js, test/functional/automatic-token-refresh.test.js, test/functional/environment.js, test/functional/jest.config.js, test/functional/jest.environment.js
- fixed mockClient targeting a different port from the one the mockServer is running on
=> GRAL-2557 fixed mockClient ports

repository.json
- updated repository owner from Pipedrive to gravity
Task :  https://pipedrive.atlassian.net/browse/GRAL-2633
=> GRAL-2633 updated repository owner

CHANGELOG.md, package-lock.json, package.json
https://pipedrive.atlassian.net/jira/software/c/projects/GRAL/boards/344?modal=detail&selectedIssue=GRAL-2883
bump superagent version
=> GRAL-2883: bump superagent version

README.md
- Added warning of global static instance usage
- Updated code examples
=> GRAL-3292 update README.md file

.github/workflows/on-pd-bot-pr-opened.yml
Fix GHA not detecting changes in CHANGELOG.md
=> Fix GHA not detecting changes in CHANGELOG.md

CODEOWNERS
- Removes CODEOWNERS file for automation to work
=> Remove codeowners for automation

package-lock.json
I tested it by running functional tests, open to other options
=> GRAL-4245: fix vulnerabilities

.github/workflows/cicd_npm-publish.yml, CHANGELOG.md, CODEOWNERS, Jenkinsfile, package.json
https://pipedrive.atlassian.net/browse/DTL-5450
=> DTL-5450 Install CI/CD for client-nodejs

package-lock.json, package.json, test/functional/utils.js
This reverts commit 5ac1837fb04268af9d801edf782b8087f13a8071, reversing changes made to 871bbb54fd2575324783b191d7cb0af1ce4d3cbd.
=> Revert "Merge pull request #578 from pipedrive/GRAL-4650"

tsconfig.json
Enables 'skipLibCheck' option during TS compile to prevent issues elsewhere.
🚧 Maintenance
=> GRAL-5406 skipLibCheck during TS compile

package-lock.json
=> GRAL-5430 fix soc vulnerability
